Repository vkamiansky/results, pull requests merged in 2020-05, with the labels that each got.

#26 i25-make-match-methods-do-the-matching
  src/Fls.Results/IOperationResult`1.cs
  src/Fls.Results/OperationResult.cs
Labels: enhancement

#22 i10 add documentation comments
  src/Fls.Results.Test/ResultFunctionsTests.cs
  src/Fls.Results/Fls.Results.csproj
  src/Fls.Results/IOperationResult`1.cs
  src/Fls.Results/OperationResult.cs
Labels: documentation

#24 Added Any and All member functions
  build/_build.csproj
  src/Fls.Results.Test/Fls.Results.Test.csproj
  src/Fls.Results.Test/ResultFunctionsTests.cs
  src/Fls.Results.sln
  src/Fls.Results/OperationResult.cs
Labels: enhancement, help wanted

#28 Methods rearranged. New asynchronous methods added
  src/Fls.Results/OperationResult.cs
Labels: enhancement

#29 Fix package publishing mechanism.
  build/Build.cs
  src/Fls.Results/Fls.Results.csproj
Labels: bug
